# Jobs to run on master after every successful merge is committed
jobs:
- job: Windows_Debug_CPU_x64
  pool: 'Win-CPU-2019'
  timeoutInMinutes: 120
  variables:
    - group: dashboard_mysql_secret
    - name: buildDirectory
      value: '$(Build.BinariesDirectory)'
    - name: BuildConfig
      value: 'Debug'
    - name: buildArch
      value: 'x64'
    - name: EnvSetupScript
      value: 'setup_env.bat'

  steps:
    - template: templates/set-test-data-variables-step.yml
    - template: templates/set-version-number-variables-step.yml

    - task: UsePythonVersion@0
      inputs: 
        versionSpec: '3.7' 
        addToPath: true 
        architecture: $(buildArch)

    - task: BatchScript@1
      displayName: 'setup env'
      inputs:
        filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\$(EnvSetupScript)'
        modifyEnvironment: true
        workingFolder: '$(Build.BinariesDirectory)'

    - task: PythonScript@0
      displayName: 'Download test data'
      inputs:
        scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\github\download_test_data.py'
        arguments: --test_data_url $(TestDataUrl) --build_dir $(Build.BinariesDirectory)
        workingDirectory: $(Build.BinariesDirectory)


    - powershell: 'Start-Process -FilePath "$(Build.BinariesDirectory)\installer\opencppcoverage\installer.exe" -ArgumentList ''/SP-'', ''/VERYSILENT'', ''/SUPPRESSMSGBOXES'', ''/NORESTART'', ''/DIR="$(Build.BinariesDirectory)\OpenCppCoverage'' -NoNewWindow -Wait'
      displayName: 'Run OpenCPPCoverage installer'

    - task: PythonScript@0
      displayName: 'Generate cmake config'
      inputs:
        scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\build.py'
        arguments: '--config $(BuildConfig) --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --build_shared_lib --update --cmake_generator "Visual Studio 16 2019" --use_openmp --build_shared_lib --enable_onnx_tests'
        workingDirectory: '$(Build.BinariesDirectory)'

    - task: VSBuild@1
      displayName: 'Build'
      inputs:
        solution: '$(Build.BinariesDirectory)\$(BuildConfig)\onnxruntime.sln'
        platform: 'x64'
        configuration: $(BuildConfig)
        msbuildArchitecture: $(buildArch)
        maximumCpuCount: true
        logProjectEvents: false
        workingFolder: '$(Build.BinariesDirectory)\$(BuildConfig)'
        createLogFile: true    

    - task: PythonScript@0
      displayName: 'test'
      inputs:
        scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\build.py'
        arguments: '--config $(BuildConfig) --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --build_shared_lib --test --cmake_generator "Visual Studio 16 2019" --use_openmp --build_shared_lib --enable_onnx_tests'
        workingDirectory: '$(Build.BinariesDirectory)'

    - template: templates/windows-code-coverage-steps.yml
      parameters:
        OpenCppCoverageExe: '$(Build.BinariesDirectory)\OpenCppCoverage\OpenCppCoverage.exe'
        GitCommitHash: $(OnnxRuntimeGitCommitHash)    
        PublishReport: true
        PostToDashboard: true

