# Defined as pipeline variables
# variables:
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

schedules:
- cron: "0 8 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

jobs: 
- template: templates/cpu.yml
  parameters:
    AgentPool : 'Win-CPU-2019'
    DoEsrp: 'true'
    DoCompliance: 'true'
