# Defined as pipeline variables
# variables:
#   AgentPoolWin : 'Win-CPU-CUDA10'
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

schedules:
- cron: "0 8 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

variables:
  PackageName: 'Microsoft.ML.OnnxRuntime.Gpu'
  TESTONGPU: 'ON'

jobs: 
- template: templates/gpu.yml
  parameters:
    AgentPool : 'Win-GPU-2019'
    DoEsrp: 'true'
